spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/budgetplanner
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  #   jpa:
  #     show-sql: true
  #     hibernate:
  #       # ddl-auto: create  # Uncomment to create tables automatically
  #       # ddl-auto: validate  # Uncomment to validate schema

  profiles:
    active: default

  security:
    oauth2:
      client:
        registration:
          cognito:
            client-id: ${COGNITO_CLIENT_ID}
            client-secret: ${COGNITO_CLIENT_SECRET}
        provider:
          cognito:
            issuer-uri: https://cognito-idp.eu-west-1.amazonaws.com/eu-west-1_5HwcQZ7mF

server:
  port: 5000
# SSL two-way TLS
# server:
#   ssl:
#     key-store: ../store/keystore.jks
#     key-store-password: ${PASSWORD}
#     key-alias: localhost
#     key-password: ${PASSWORD}
#     enabled: true
#     protocol: TLS
#     enabled-protocols: TLSv1.2

# spring:
#   security:
#     user:
#       name: Admin
#       password: admin
